version: '3.8'

services:
  # Local MongoDB Container
  mongodb:
    image: mongo:latest
    container_name: mstry_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # Local Redis Container
  redis:
    image: redis:alpine
    container_name: mstry_redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel notice

volumes:
  mongo_data: